config/routes.rb
Rails.application.routes.draw do
  resources :resources
  resources :technologies
  resources :clients
  resources :trainings
  resources :training_resources
  resources :projects
  resources :activities
  resources :assignments
  resources :assignments
  devise_for :users
  devise_for :admins
  resources :resources
  get 'home/index'

  root 'resources#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/technology.rb
class Technology < ActiveRecord::Base
end

app/models/training.rb
class Training < ActiveRecord::Base
end

app/models/training_resource.rb
class TrainingResource < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_filter :authenticate_user!

  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name_client, :email, :username, :password, :contact, :address, :is_experienced, :notes, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	  before_filter :authenticate_user!

  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_filter :authenticate_user!

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :coordinator, :category, :notes, :start_date, :deadline, :finish_date)
    end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
    before_filter :authenticate_user!

  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: 'Resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:name, :job_title, :email, :username, :password, :cnic, :experience, :status, :require_training, :date_added, :date_updated)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/clients/_form.html.erb
<ol class="breadcrumb">
          <li>
            <a href="dashboard.php">
              <i class="entypo-folder"></i>
              Dashboard
            </a>
          </li>
          <li><a href="#">Clients</a></li>
          <li class="active"><a href="/clients/new">Add New Client</a></li>
          <li><a href="/clients">All Clients</a></li>
        </ol>
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name_client %><br>
    <%= f.text_field :name_client, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :username %><br>
    <%= f.text_field :username, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :contact %><br>
    <%= f.text_field :contact, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_area :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :is_experienced %><br>
    <%= f.select(:is_experienced, options_for_select([['Yes'], ['No']]), {}, {class: "form-control"}) %>
  </div>
  <div class="form-group">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.text_field :status, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name client</th>
      <th>Email</th>
      <th>Username</th>
      <th>Password</th>
      <th>Contact</th>
      <th>Address</th>
      <th>Is experienced</th>
      <th>Notes</th>
      <th>Status</th>
<th colspan="3" style="text-align:center;">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name_client %></td>
        <td><%= client.email %></td>
        <td><%= client.username %></td>
        <td><%= client.password %></td>
        <td><%= client.contact %></td>
        <td><%= client.address %></td>
        <td><%= client.is_experienced %></td>
        <td><%= client.notes %></td>
        <td><%= client.status %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name client:</strong>
  <%= @client.name_client %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @client.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @client.password %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @client.contact %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Is experienced:</strong>
  <%= @client.is_experienced %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @client.notes %>
</p>

<p>
  <strong>Status:</strong>
  <%= @client.status %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/projects/_form.html.erb
<ol class="breadcrumb">
          <li>
            <a href="dashboard.php">
              <i class="entypo-folder"></i>
              Dashboard
            </a>
          </li>
          <li><a href="#">Projects</a></li>
          <li class="active"><a href="/projects/new">Add New Project</a></li>
          <li><a href="/projects">All Projects</a></li>
        </ol>
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :coordinator %><br>
    <%= f.text_field :coordinator, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.select(:category, options_for_select([['Personal'], ['Office'], ['Commercial']]), {}, {class: "form-control"}) %>
  </div>
  <div class="form-group">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :deadline %><br>
    <%= f.date_field :deadline, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :finish_date %><br>
    <%= f.date_field :finish_date, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Coordinator</th>
      <th>Category</th>
      <th>Notes</th>
      <th>Start date</th>
      <th>Deadline</th>
      <th>Finish date</th>
<th colspan="3" style="text-align:center;">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.coordinator %></td>
        <td><%= project.category %></td>
        <td><%= project.notes %></td>
        <td><%= project.start_date %></td>
        <td><%= project.deadline %></td>
        <td><%= project.finish_date %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Coordinator:</strong>
  <%= @project.coordinator %>
</p>

<p>
  <strong>Category:</strong>
  <%= @project.category %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @project.notes %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @project.deadline %>
</p>

<p>
  <strong>Finish date:</strong>
  <%= @project.finish_date %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>