config/routes.rb
Rails.application.routes.draw do
  resources :resources
  resources :technologies
  resources :clients
  resources :trainings
  resources :training_resources
  resources :projects
  resources :activities
  resources :assignments
  resources :assignments
  devise_for :users
  devise_for :admins
  resources :resources
  get 'home/index'

  root 'resources#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/technology.rb
class Technology < ActiveRecord::Base
end

app/models/training.rb
class Training < ActiveRecord::Base
end

app/models/training_resource.rb
class TrainingResource < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	  before_filter :authenticate_user!

  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang='en'>
<nav class="navbar" role="navigation">
	<div class="row">
	
	<!-- Profile Info and Notifications -->
	<div class="col-md-6 col-sm-8 clearfix">
		
		<ul class="user-info pull-left pull-none-xsm">
		
						<!-- Profile Info -->
			<li class="profile-info dropdown"><!-- add class "pull-right" if you want to place this from right -->
				
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<%= image_tag("thumb-1@2x.png", class: 'img-circle my') %>
					Art Ramadani
				</a>
				
				<ul class="dropdown-menu">
					
					<!-- Reverse Caret -->
					<li class="caret"></li>
					
					<!-- Profile sub-links -->
					<li>
						<a href="/users/edit">
							<i class="entypo-user"></i>
							Edit Profile
						</a>
					</li>
					
					<li>
						<a href="mailbox.html">
							<i class="entypo-mail"></i>
							Inbox
						</a>
					</li>
					
					<li>
						<a href="extra-calendar.html">
							<i class="entypo-calendar"></i>
							Calendar
						</a>
					</li>
					
					<li>
						<a href="#">
							<i class="entypo-clipboard"></i>
							Tasks
						</a>
					</li>
				</ul>
			</li>
		
		</ul>
				
		<ul class="user-info pull-left pull-right-xs pull-none-xsm">
			
			<!-- Raw Notifications -->
			<li class="notifications dropdown">
				
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
					<i class="entypo-attention"></i>
					<span class="badge badge-info">6</span>
				</a>
				
				<ul class="dropdown-menu">
					<li class="top">
	<p class="small">
		<a href="#" class="pull-right">Mark all Read</a>
		You have <strong>3</strong> new notifications.
	</p>
</li>

<li>
	<ul class="dropdown-menu-list scroller">
		<li class="unread notification-success">
			<a href="#">
				<i class="entypo-user-add pull-right"></i>
				
				<span class="line">
					<strong>New user registered</strong>
				</span>
				
				<span class="line small">
					30 seconds ago
				</span>
			</a>
		</li>
		
		<li class="unread notification-secondary">
			<a href="#">
				<i class="entypo-heart pull-right"></i>
				
				<span class="line">
					<strong>Someone special liked this</strong>
				</span>
				
				<span class="line small">
					2 minutes ago
				</span>
			</a>
		</li>
		
		<li class="notification-primary">
			<a href="#">
				<i class="entypo-user pull-right"></i>
				
				<span class="line">
					<strong>Privacy settings have been changed</strong>
				</span>
				
				<span class="line small">
					3 hours ago
				</span>
			</a>
		</li>
		
		<li class="notification-danger">
			<a href="#">
				<i class="entypo-cancel-circled pull-right"></i>
				
				<span class="line">
					John cancelled the event
				</span>
				
				<span class="line small">
					9 hours ago
				</span>
			</a>
		</li>
		
		<li class="notification-info">
			<a href="#">
				<i class="entypo-info pull-right"></i>
				
				<span class="line">
					The server is status is stable
				</span>
				
				<span class="line small">
					yesterday at 10:30am
				</span>
			</a>
		</li>
		
		<li class="notification-warning">
			<a href="#">
				<i class="entypo-rss pull-right"></i>
				
				<span class="line">
					New comments waiting approval
				</span>
				
				<span class="line small">
					last week
				</span>
			</a>
		</li>
	</ul>
</li>

<li class="external">
	<a href="#">View all notifications</a>
</li>				</ul>
				
			</li>
			
			<!-- Message Notifications -->
			<li class="notifications dropdown">
				
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
					<i class="entypo-mail"></i>
					<span class="badge badge-secondary">10</span>
				</a>
				
				<ul class="dropdown-menu">
					<li>
	<ul class="dropdown-menu-list scroller">
		<li class="active">
			<a href="#">
				<span class="image pull-right">
					<%= image_tag("thumb-1.png", class: 'img-circle thumb') %>
				</span>
				
				<span class="line">
					<strong>Luc Chartier</strong>
					- yesterday
				</span>
				
				<span class="line desc small">
					This ain’t our first item, it is the best of the rest.
				</span>
			</a>
		</li>
		
		<li>
			<a href="#">
				<span class="image pull-right">
					<%= image_tag("thumb-3.png", class: 'img-circle thumb') %>
				</span>
				
				<span class="line">
					Hayden Cartwright
					- a week ago
				</span>
				
				<span class="line desc small">
					Whose her enjoy chief new young. Felicity if ye required likewise so doubtful.
				</span>
			</a>
		</li>
		
		<li>
			<a href="#">
				<span class="image pull-right">
					<%= image_tag("thumb-4.png", class: 'img-circle thumb') %>
				</span>
				
				<span class="line">
					Sandra Eberhardt
					- 16 days ago
				</span>
				
				<span class="line desc small">
					On so attention necessary at by provision otherwise existence direction.
				</span>
			</a>
		</li>
	</ul>
</li>

<li class="external">
	<a href="mailbox.html">All Messages</a>
</li>				</ul>
				
			</li>
			
			<!-- Task Notifications -->
			<li class="notifications dropdown">
				
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
					<i class="entypo-list"></i>
					<span class="badge badge-warning">1</span>
				</a>
				
				<ul class="dropdown-menu">
					<li class="top">
	<p>You have 6 pending tasks</p>
</li>

<li>
	<ul class="dropdown-menu-list scroller">
		<li>
			<a href="#">
				<span class="task">
					<span class="desc">Procurement</span>
					<span class="percent">27%</span>
				</span>
			
				<span class="progress">
					<span style="width: 27%;" class="progress-bar progress-bar-success">
						<span class="sr-only">27% Complete</span>
					</span>
				</span>
			</a>
		</li>
		<li>
			<a href="#">
				<span class="task">
					<span class="desc">App Development</span>
					<span class="percent">83%</span>
				</span>
				
				<span class="progress progress-striped">
					<span style="width: 83%;" class="progress-bar progress-bar-danger">
						<span class="sr-only">83% Complete</span>
					</span>
				</span>
			</a>
		</li>
		<li>
			<a href="#">
				<span class="task">
					<span class="desc">HTML Slicing</span>
					<span class="percent">91%</span>
				</span>
				
				<span class="progress">
					<span style="width: 91%;" class="progress-bar progress-bar-success">
						<span class="sr-only">91% Complete</span>
					</span>
				</span>
			</a>
		</li>
		<li>
			<a href="#">
				<span class="task">
					<span class="desc">Database Repair</span>
					<span class="percent">12%</span>
				</span>
				
				<span class="progress progress-striped">
					<span style="width: 12%;" class="progress-bar progress-bar-warning">
						<span class="sr-only">12% Complete</span>
					</span>
				</span>
			</a>
		</li>
		<li>
			<a href="#">
				<span class="task">
					<span class="desc">Backup Create Progress</span>
					<span class="percent">54%</span>
				</span>
				
				<span class="progress progress-striped">
					<span style="width: 54%;" class="progress-bar progress-bar-info">
						<span class="sr-only">54% Complete</span>
					</span>
				</span>
			</a>
		</li>
		<li>
			<a href="#">
				<span class="task">
					<span class="desc">Upgrade Progress</span>
					<span class="percent">17%</span>
				</span>
				
				<span class="progress progress-striped">
					<span style="width: 17%;" class="progress-bar progress-bar-important">
						<span class="sr-only">17% Complete</span>
					</span>
				</span>
			</a>
		</li>
	</ul>
</li>

<li class="external">
	<a href="#">See all tasks</a>
</li>				</ul>
				
			</li>
		
		</ul>
	
	</div>
	
	
	<!-- Raw Links -->
	<div class="col-md-6 col-sm-4 clearfix hidden-xs">
		
		<ul class="list-inline links-list pull-right">
			
			<!-- Language Selector -->			<li class="dropdown language-selector">
				
				Language: &nbsp;
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-close-others="true">
					<%= image_tag("flag-uk.png") %>
				</a>
				
				<ul class="dropdown-menu pull-right">
					<li>
						<a href="#">
							<%= image_tag("flag-de.png") %>
							<span>Deutsch</span>
						</a>
					</li>
					<li class="active">
						<a href="#">
							<%= image_tag("flag-uk.png") %>
							<span>English</span>
						</a>
					</li>
					<li>
						<a href="#">
							<%= image_tag("flag-fr.png") %>
							<span>François</span>
						</a>
					</li>
					<li>
						<a href="#">
							<%= image_tag("flag-al.png") %>
							<span>Shqip</span>
						</a>
					</li>
					<li>
						<a href="#">
							<%= image_tag("flag-es.png") %>
							<span>Español</span>
						</a>
					</li>
				</ul>
				
			</li>
			
			<li class="sep"></li>
			
						
			<li>
				<a href="#" data-toggle="chat" data-animate="1" data-collapse-sidebar="1">
					<i class="entypo-chat"></i>
					Chat
					
					<span class="badge badge-success chat-notifications-badge is-hidden">0</span>
				</a>
			</li>
			
			<li class="sep"></li>
			
			<li>
				        <% if user_signed_in? %>
				        <li><%= link_to "Signout", destroy_user_session_path, method: :delete %></li> <i class="entypo-logout right"></i>
				        <% else %>
				        <li><%= link_to "Signin", new_user_session_path %></li> <i class="entypo-logout right"></i>
				        <% end %>
				</a>
			</li>
		</ul>
		
	</div>
	
</div>
</nav
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PMS</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'jquery-1', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'neon-core', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'neon-theme', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'neon-forms', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'entypo', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'animation', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'entypo-codes', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'entypo-embedded', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'jquery-jvectormap-1.2.2', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'main', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'main-gsap', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'bootstrap', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'joinable', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'resizeable', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'neon-api', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'jquery-sparkline', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'rikshaw.min', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'raphael-min', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'morris-min', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'toastr', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'neon-chat', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'neon-custom', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'neon-demo', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'less', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'neon-skins', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'scrollMonitor', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    
    <%= render 'layouts/navigation' %>   
    <p class="alert"><%= alert %></p>
    <div class="container">
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-10">
      <%= yield %>
  </div>
</div>
</div>

    
  </body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %><br>
    <%= f.text_field :job_title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :username %><br>
    <%= f.text_field :username, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :cnic %><br>
    <%= f.text_field :cnic, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :experience %><br>
    <%= f.text_field :experience, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.select(:status, options_for_select([['Admin'], ['Employee']]), {}, {class: "form-control"}) %>
  </div>
  <div class="form-group">
    <%= f.label :require_training %><br>
    <%= f.select(:require_training, options_for_select([['Yes'], ['No']]), {}, {class: "form-control"}) %>
  </div>
  <div class="form-group">
    <%= f.label :date_added %><br>
    <%= f.date_field :date_added, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :date_updated %><br>
    <%= f.date_field :date_updated, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Job title</th>
      <th>Email</th>
      <th>Username</th>
      <th>Password</th>
      <th>Cnic</th>
      <th>Experience</th>
      <th>Status</th>
      <th>Require training</th>
      <th>Date added</th>
      <th>Date updated</th>
<th colspan="3" style="text-align:center;">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.job_title %></td>
        <td><%= resource.email %></td>
        <td><%= resource.username %></td>
        <td><%= resource.password %></td>
        <td><%= resource.cnic %></td>
        <td><%= resource.experience %></td>
        <td><%= resource.status %></td>
        <td><%= resource.require_training %></td>
        <td><%= resource.date_added %></td>
        <td><%= resource.date_updated %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-hover">
  <tr>
<td>
  <strong>Name:</strong>
</td>
<td>
  <%= @resource.name %>
</td>
</tr>
<tr>
<td>
  <strong>Job title:</strong>
</td>
<td>
  <%= @resource.job_title %>
</td>
</tr>
<tr>
<td>
  <strong>Email:</strong>
</td>
<td>
  <%= @resource.email %>
</td>
</tr>
<tr>
<td>
  <strong>Username:</strong>
</td>
<td>
  <%= @resource.username %>
</td>
</tr>
<tr>
<td>
  <strong>Password:</strong>
  </td>
    <td>
  <%= @resource.password %>
</td>
</tr>
<tr>
<td>
  <strong>Cnic:</strong>
</td>
<td>
  <%= @resource.cnic %>
</td>
</tr>
<tr>
<td>
  <strong>Experience:</strong>
</td>
<td>
  <%= @resource.experience %>
</td>
</tr>
<tr>
<td>
  <strong>Status:</strong>
</td>
<td>
  <%= @resource.status %>
</td>
</tr>
<tr>
<td>
  <strong>Require training:</strong>
</td>
<td>
  <%= @resource.require_training %>
</td>
</tr>
<tr>
<td>
  <strong>Date added:</strong>
</td>
<td>
  <%= @resource.date_added %>
</td>
</tr>
<tr>
<td>
  <strong>Date updated:</strong>
</td>
<td>
  <%= @resource.date_updated %>
</td>
</tr>
</table>
<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>