config/routes.rb
Rails.application.routes.draw do
  resources :resources
  resources :technologies
  resources :clients
  resources :trainings
  resources :training_resources
  resources :projects
  resources :activities
  resources :assignments
  resources :assignments
  devise_for :users
  devise_for :admins
  resources :resources
  get 'home/index'

  root 'resources#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/technology.rb
class Technology < ActiveRecord::Base
end

app/models/training.rb
class Training < ActiveRecord::Base
end

app/models/training_resource.rb
class TrainingResource < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_filter :authenticate_user!

  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name_client, :email, :username, :password, :contact, :address, :is_experienced, :notes, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	  before_filter :authenticate_user!

  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_filter :authenticate_user!

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :coordinator, :category, :notes, :start_date, :deadline, :finish_date)
    end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
    before_filter :authenticate_user!

  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technology_params
      params.require(:technology).permit(:name_technology)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/technologies/_form.html.erb
<ol class="breadcrumb">
          <li>
            <a href="dashboard.php">
              <i class="entypo-folder"></i>
              Dashboard
            </a>
          </li>
          <li><a href="#">Technologies</a></li>
          <li class="active"><a href="/technologies/new">Add New Technology</a></li>
          <li><a href="/technologies">All Technologies</a></li>
        </ol>
<%= form_for(@technology) do |f| %>
  <% if @technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
      <% @technology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name_technology %><br>
    <%= f.text_field :name_technology, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/technologies/edit.html.erb
<h1>Editing Technology</h1>

<%= render 'form' %>

<%= link_to 'Show', @technology %> |
<%= link_to 'Back', technologies_path %>

app/views/technologies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Technologies</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name technology</th>
<th colspan="3" style="text-align:center;">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= technology.name_technology %></td>
        <td><%= link_to 'Show', technology %></td>
        <td><%= link_to 'Edit', edit_technology_path(technology) %></td>
        <td><%= link_to 'Destroy', technology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Technology', new_technology_path %>

app/views/technologies/new.html.erb
<h1>New Technology</h1>

<%= render 'form' %>

<%= link_to 'Back', technologies_path %>

app/views/technologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name technology:</strong>
  <%= @technology.name_technology %>
</p>

<%= link_to 'Edit', edit_technology_path(@technology) %> |
<%= link_to 'Back', technologies_path %>